drop table college_football_play_by_play_data;
create table college_football_play_by_play_data
(
    index                                     double precision,
    year                                      int,
    week                                      int,
    id_play                                   double precision,
    game_id                                   int,
    game_play_number                          int,
    half_play_number                          double precision,
    drive_play_number                         double precision,
    pos_team                                  varchar(255),
    def_pos_team                              varchar(255),
    pos_team_score                            int,
    def_pos_team_score                        int,
    half                                      int,
    period                                    int,
    clock_minutes                             double precision,
    clock_seconds                             double precision,
    play_type                                 varchar(255),
    play_text                                 varchar(2550),
    down                                      double precision,
    distance                                  double precision,
    yards_to_goal                             double precision,
    yards_gained                              int,
    epa                                       double precision,
    ep_before                                 double precision,
    ep_after                                  double precision,
    wpa                                       double precision,
    wp_before                                 double precision,
    wp_after                                  double precision,
    def_wp_before                             double precision,
    def_wp_after                              double precision,
    penalty_detail                            varchar(255),
    yds_penalty                               double precision,
    penalty_1st_conv                          boolean,
    new_series                                double precision,
    firstd_by_kickoff                         double precision,
    firstd_by_poss                            double precision,
    firstd_by_penalty                         double precision,
    firstd_by_yards                           double precision,
    def_epa                                   double precision,
    home_epa                                  double precision,
    away_epa                                  double precision,
    home_epa_rush                             double precision,
    away_epa_rush                             double precision,
    home_epa_pass                             double precision,
    away_epa_pass                             double precision,
    total_home_epa                            double precision,
    total_away_epa                            double precision,
    total_home_epa_rush                       double precision,
    total_away_epa_rush                       double precision,
    total_home_epa_pass                       double precision,
    total_away_epa_pass                       double precision,
    net_home_epa                              double precision,
    net_away_epa                              double precision,
    net_home_epa_rush                         double precision,
    net_away_epa_rush                         double precision,
    net_home_epa_pass                         double precision,
    net_away_epa_pass                         double precision,
    success                                   double precision,
    epa_success                               double precision,
    rz_play                                   int,
    scoring_opp                               int,
    middle_8                                  boolean,
    stuffed_run                               int,
    change_of_pos_team                        int,
    downs_turnover                            int,
    turnover                                  double precision,
    pos_score_diff_start                      double precision,
    pos_score_pts                             double precision,
    log_ydstogo                               double precision,
    expscorediff                              double precision,
    expscorediff_time_ratio                   double precision,
    half_clock_minutes                        double precision,
    timesecsrem                               int,
    adj_timesecsrem                           double precision,
    goal_to_go                                varchar(255),
    under_two                                 varchar(255),
    home                                      varchar(255),
    away                                      varchar(255),
    home_wp_before                            double precision,
    away_wp_before                            double precision,
    home_wp_after                             double precision,
    away_wp_after                             double precision,
    end_of_half                               varchar(255),
    pos_team_receives_2h_kickoff              int,
    lead_pos_team                             varchar(255),
    lead_play_type                            varchar(255),
    lag_pos_team                              varchar(255),
    lag_play_type                             varchar(255),
    orig_play_type                            varchar(255),
    under_three                               varchar(255),
    down_end                                  double precision,
    distance_end                              double precision,
    log_ydstogo_end                           double precision,
    yards_to_goal_end                         double precision,
    timesecsrem_end                           double precision,
    goal_to_go_end                            varchar(255),
    under_two_end                             varchar(255),
    offense_score_play                        int,
    defense_score_play                        int,
    ppa                                       double precision,
    yard_line                                 int,
    scoring                                   varchar(255),
    pos_team_timeouts_rem_before              double precision,
    def_pos_team_timeouts_rem_before          double precision,
    pos_team_timeouts                         double precision,
    def_pos_team_timeouts                     double precision,
    pos_score_diff                            double precision,
    pos_score_diff_start_end                  double precision,
    offense_play                              varchar(255),
    defense_play                              varchar(255),
    offense_receives_2h_kickoff               double precision,
    change_of_poss                            int,
    score_pts                                 double precision,
    score_diff_start                          double precision,
    score_diff                                double precision,
    offense_score                             double precision,
    defense_score                             double precision,
    offense_conference                        varchar(255),
    defense_conference                        varchar(255),
    off_timeout_called                        double precision,
    def_timeout_called                        double precision,
    offense_timeouts                          double precision,
    defense_timeouts                          double precision,
    off_timeouts_rem_before                   double precision,
    def_timeouts_rem_before                   double precision,
    rusher_player_name                        varchar(255),
    yds_rushed                                double precision,
    passer_player_name                        varchar(255),
    receiver_player_name                      varchar(255),
    yds_receiving                             double precision,
    yds_sacked                                double precision,
    sack_players                              varchar(255),
    sack_player_name                          varchar(255),
    sack_player_name2                         varchar(255),
    pass_breakup_player_name                  varchar(255),
    interception_player_name                  varchar(255),
    yds_int_return                            double precision,
    fumble_player_name                        varchar(255),
    fumble_forced_player_name                 varchar(255),
    fumble_recovered_player_name              varchar(255),
    yds_fumble_return                         double precision,
    punter_player_name                        varchar(255),
    yds_punted                                double precision,
    punt_returner_player_name                 varchar(255),
    yds_punt_return                           double precision,
    yds_punt_gained                           double precision,
    punt_block_player_name                    varchar(255),
    punt_block_return_player_name             varchar(255),
    fg_kicker_player_name                     varchar(255),
    yds_fg                                    double precision,
    fg_block_player_name                      varchar(255),
    fg_return_player_name                     varchar(255),
    kickoff_player_name                       varchar(255),
    yds_kickoff                               double precision,
    kickoff_returner_player_name              varchar(255),
    yds_kickoff_return                        double precision,
    new_id                                    double precision,
    orig_drive_number                         double precision,
    drive_number                              double precision,
    drive_result_detailed                     varchar(255),
    new_drive_pts                             double precision,
    drive_id                                  varchar(255),
    drive_result                              varchar(255),
    drive_start_yards_to_goal                 double precision,
    drive_end_yards_to_goal                   double precision,
    drive_yards                               double precision,
    drive_scoring                             double precision,
    drive_pts                                 double precision,
    drive_start_period                        double precision,
    drive_end_period                          double precision,
    drive_time_minutes_start                  double precision,
    drive_time_seconds_start                  double precision,
    drive_time_minutes_end                    double precision,
    drive_time_seconds_end                    double precision,
    drive_time_minutes_elapsed                double precision,
    drive_time_seconds_elapsed                double precision,
    drive_numbers                             double precision,
    number_of_drives                          double precision,
    pts_scored                                double precision,
    drive_result_detailed_flag                varchar(255),
    drive_result2                             varchar(255),
    drive_num                                 double precision,
    lag_drive_result_detailed                 varchar(255),
    lead_drive_result_detailed                varchar(255),
    lag_new_drive_pts                         double precision,
    id_drive                                  double precision,
    rush                                      varchar(255),
    rush_td                                   int,
    pass                                      varchar(255),
    pass_td                                   int,
    completion                                int,
    pass_attempt                              int,
    target                                    int,
    sack_vec                                  int,
    sack                                      int,
    int                                       int,
    int_td                                    int,
    turnover_vec                              int,
    turnover_vec_lag                          double precision,
    turnover_indicator                        double precision,
    kickoff_play                              varchar(255),
    receives_2h_kickoff                       double precision,
    missing_yard_flag                         varchar(255),
    scoring_play                              int,
    td_play                                   varchar(255),
    touchdown                                 int,
    safety                                    varchar(255),
    fumble_vec                                double precision,
    kickoff_tb                                varchar(255),
    kickoff_onside                            varchar(255),
    kickoff_oob                               varchar(255),
    kickoff_fair_catch                        varchar(255),
    kickoff_downed                            varchar(255),
    kickoff_safety                            varchar(255),
    kick_play                                 varchar(255),
    punt                                      varchar(255),
    punt_play                                 varchar(255),
    punt_tb                                   varchar(255),
    punt_oob                                  varchar(255),
    punt_fair_catch                           varchar(255),
    punt_downed                               varchar(255),
    punt_safety                               varchar(255),
    punt_blocked                              varchar(255),
    penalty_safety                            double precision,
    fg_inds                                   double precision,
    fg_made                                   varchar(255),
    fg_make_prob                              double precision,
    no_score_before                           double precision,
    fg_before                                 double precision,
    opp_fg_before                             double precision,
    opp_safety_before                         double precision,
    opp_td_before                             double precision,
    safety_before                             double precision,
    td_before                                 double precision,
    no_score_after                            double precision,
    fg_after                                  double precision,
    opp_fg_after                              double precision,
    opp_safety_after                          double precision,
    opp_td_after                              double precision,
    safety_after                              double precision,
    td_after                                  double precision,
    position_reception                        varchar(255),
    position_target                           varchar(255),
    position_completion                       varchar(255),
    position_incompletion                     varchar(255),
    position_sack_taken                       varchar(255),
    position_sack                             varchar(255),
    position_interception_thrown              varchar(255),
    position_interception                     varchar(255),
    position_fumble                           varchar(255),
    position_fumble_forced                    varchar(255),
    position_fumble_recovered                 varchar(255),
    position_pass_breakup                     varchar(255),
    position_rush                             varchar(255),
    position_touchdown                        varchar(255),
    season                                    double precision,
    opponent                                  varchar(255),
    team_score                                double precision,
    opponent_score                            double precision,
    rush_player_id                            double precision,
    rush_player                               varchar(255),
    rush_yds                                  double precision,
    reception_player_id                       double precision,
    reception_player                          varchar(255),
    reception_yds                             double precision,
    completion_player_id                      double precision,
    completion_player                         varchar(255),
    completion_yds                            double precision,
    interception_player_id                    double precision,
    interception_player                       varchar(255),
    interception_stat                         double precision,
    interception_thrown_player_id             double precision,
    interception_thrown_player                varchar(255),
    interception_thrown_stat                  double precision,
    touchdown_player_id                       double precision,
    touchdown_player                          varchar(255),
    touchdown_stat                            double precision,
    incompletion_player_id                    double precision,
    incompletion_player                       varchar(255),
    incompletion_stat                         double precision,
    target_player_id                          double precision,
    target_player                             varchar(255),
    target_stat                               double precision,
    fumble_recovered_player_id                double precision,
    fumble_recovered_player                   varchar(255),
    fumble_recovered_stat                     double precision,
    fumble_forced_player_id                   double precision,
    fumble_forced_player                      varchar(255),
    fumble_forced_stat                        double precision,
    fumble_player_id                          double precision,
    fumble_player                             varchar(255),
    fumble_stat                               double precision,
    sack_player_id                            double precision,
    sack_player                               varchar(255),
    sack_stat                                 double precision,
    sack_taken_player_id                      double precision,
    sack_taken_player                         varchar(255),
    sack_taken_stat                           double precision,
    pass_breakup_player_id                    double precision,
    pass_breakup_player                       varchar(255),
    pass_breakup_stat                         double precision,
    play_id                                   double precision,
    penalty_flag                              boolean,
    penalty_declined                          boolean,
    penalty_no_play                           boolean,
    penalty_offset                            boolean,
    penalty_text                              varchar(2550),
    penalty_play_text                         varchar(2550),
    row                                       double precision,
    drive_event_number                        double precision,
    lag_play_type2                            varchar(255),
    lag_play_type3                            varchar(255),
    lag_play_text                             varchar(2550),
    lag_play_text2                            varchar(2550),
    lead_play_text                            varchar(2550),
    lag_first_by_penalty                      double precision,
    lag_first_by_penalty2                     double precision,
    lag_first_by_yards                        double precision,
    lag_first_by_yards2                       double precision,
    first_by_penalty                          double precision,
    first_by_yards                            double precision,
    play_after_turnover                       double precision,
    lag_change_of_poss                        double precision,
    lag_change_of_pos_team                    double precision,
    lag_change_of_pos_team2                   double precision,
    lag_kickoff_play                          double precision,
    lag_punt                                  double precision,
    lag_punt2                                 double precision,
    lag_scoring_play                          varchar(255),
    lag_turnover_vec                          double precision,
    lag_downs_turnover                        double precision,
    lag_defense_score_play                    double precision,
    home_score                                double precision,
    priority                                  varchar(255),
    away_score                                double precision,
    date                                      varchar(255),
    text                                      varchar(2550),
    type_id                                   double precision,
    end_yard_line                             double precision,
    end_yards_to_endzone                      double precision,
    drive_description                         varchar(255),
    drive_short_display_result                varchar(255),
    season_type                               double precision,
    home_team_spread                          double precision,
    game_spread                               double precision,
    home_favorite                             varchar(255),
    game_spread_available                     varchar(255),
    time                                      varchar(255),
    clock_minutes_2                           double precision,
    clock_seconds_2                           double precision,
    start_quarter_seconds_remaining           double precision,
    start_game_seconds_remaining              double precision,
    end_defteam_name                          varchar(255),
    home_timeout_called                       varchar(255),
    away_timeout_called                       varchar(255),
    end_quarter_seconds_remaining             double precision,
    end_game_seconds_remaining                double precision,
    end_posteam_timeouts                      double precision,
    end_yard                                  double precision,
    end_yardline_100                          double precision,
    scoring_play_2                            varchar(255),
    start_away_score                          double precision,
    end_home_score                            double precision,
    posteam_score_pts                         double precision,
    end_posteam_receives_2h_kickoff           varchar(255),
    penalty_in_text                           varchar(255),
    pos_unit                                  varchar(255),
    def_pos_unit                              varchar(255),
    special_teams                             varchar(255),
    play                                      varchar(255),
    scrimmage_play                            varchar(255),
    posteam_score_differential_end            double precision,
    kickoff_return_player_name                double precision,
    fumble_recovery_player_name               varchar(255),
    punt_blocked_returner_player_name         double precision,
    fg_blocked_player_name                    double precision,
    punt_blocked_player_name                  double precision,
    blocked_player_name                       double precision,
    kicker_player_name                        varchar(255),
    kick_returner_player_name                 varchar(255),
    new_down                                  double precision,
    new_ydstogo                               double precision,
    stopped_run                               varchar(255),
    opportunity_run                           varchar(255),
    highlight_run                             varchar(255),
    short_rush_success                        varchar(255),
    short_rush_attempt                        varchar(255),
    power_rush_success                        varchar(255),
    power_rush_attempt                        varchar(255),
    standard_down                             varchar(255),
    passing_down                              varchar(255),
    tfl                                       varchar(255),
    tfl_pass                                  varchar(255),
    tfl_rush                                  varchar(255),
    havoc                                     varchar(255),
    havoc_pass                                varchar(255),
    havoc_rush                                varchar(255),
    start_posteam_spread                      double precision,
    start_elapsed_share                       double precision,
    start_spread_time                         double precision,
    end_posteam_spread                        double precision,
    end_elapsed_share                         double precision,
    end_spread_time                           double precision,
    ydstogo                                   double precision,
    ep_start_touchback                        double precision,
    ep_start                                  double precision,
    ep_end                                    double precision,
    lag_ep_end                                double precision,
    lag_change_of_posteam                     varchar(255),
    ep_between                                double precision,
    epa_scrimmage                             double precision,
    epa_rush                                  double precision,
    epa_pass                                  double precision,
    epa_explosive                             varchar(255),
    epa_explosive_pass                        varchar(255),
    epa_explosive_rush                        varchar(255),
    epa_success_standard_down                 varchar(255),
    epa_success_passing_down                  varchar(255),
    epa_success_pass                          varchar(255),
    epa_success_rush                          varchar(255),
    epa_success_epa                           double precision,
    epa_success_standard_down_epa             double precision,
    epa_success_passing_down_epa              double precision,
    epa_success_pass_epa                      double precision,
    epa_success_rush_epa                      varchar(255),
    epa_penalty                               double precision,
    epa_special_teams                         double precision,
    epa_fg                                    double precision,
    epa_punt                                  double precision,
    epa_kickoff                               double precision,
    start_exp_score_diff_touchback            double precision,
    start_exp_score_diff                      double precision,
    start_exp_score_diff_time_ratio_touchback double precision,
    start_exp_score_diff_time_ratio           double precision,
    end_exp_score_diff                        double precision,
    end_exp_score_diff_time_ratio             double precision,
    wp_touchback                              double precision,
    lead_wp_before                            double precision,
    lead_wp_before2                           double precision,
    wpa_base                                  double precision,
    wpa_base_nxt                              double precision,
    wpa_base_nxt2                             double precision,
    wpa_base_ind                              varchar(255),
    wpa_base_nxt_ind                          varchar(255),
    wpa_base_nxt2_ind                         varchar(255),
    wpa_change                                double precision,
    wpa_change_nxt                            double precision,
    wpa_change_nxt2                           double precision,
    wpa_change_ind                            varchar(255),
    wpa_change_nxt_ind                        varchar(255),
    wpa_change_nxt2_ind                       varchar(255),
    wpa_half_end                              double precision,
    drive_start                               double precision,
    drive_play_index                          double precision,
    prog_drive_epa                            double precision,
    prog_drive_wpa                            double precision,
    drive_offense_yards                       double precision,
    drive_total_yards                         double precision,
    media_id                                  double precision
);
copy college_football_play_by_play_data(index, year, week, id_play, game_id, game_play_number, half_play_number, drive_play_number, pos_team, def_pos_team, pos_team_score,
                                        def_pos_team_score, half, period, clock_minutes, clock_seconds, play_type, play_text, down, distance, yards_to_goal, yards_gained, epa, ep_before,
                                        ep_after, wpa, wp_before, wp_after, def_wp_before, def_wp_after, penalty_detail, yds_penalty, penalty_1st_conv, new_series, firstd_by_kickoff,
                                        firstd_by_poss, firstd_by_penalty, firstd_by_yards, def_epa, home_epa, away_epa, home_epa_rush, away_epa_rush, home_epa_pass, away_epa_pass,
                                        total_home_epa, total_away_epa, total_home_epa_rush, total_away_epa_rush, total_home_epa_pass, total_away_epa_pass, net_home_epa, net_away_epa,
                                        net_home_epa_rush, net_away_epa_rush, net_home_epa_pass, net_away_epa_pass, success, epa_success, rz_play, scoring_opp, middle_8, stuffed_run,
                                        change_of_pos_team, downs_turnover, turnover, pos_score_diff_start, pos_score_pts, log_ydstogo, expscorediff, expscorediff_time_ratio,
                                        half_clock_minutes, timesecsrem, adj_timesecsrem, goal_to_go, under_two, home, away, home_wp_before, away_wp_before, home_wp_after, away_wp_after,
                                        end_of_half, pos_team_receives_2h_kickoff, lead_pos_team, lead_play_type, lag_pos_team, lag_play_type, orig_play_type, under_three, down_end,
                                        distance_end, log_ydstogo_end, yards_to_goal_end, timesecsrem_end, goal_to_go_end, under_two_end, offense_score_play, defense_score_play, ppa,
                                        yard_line, scoring, pos_team_timeouts_rem_before, def_pos_team_timeouts_rem_before, pos_team_timeouts, def_pos_team_timeouts, pos_score_diff,
                                        pos_score_diff_start_end, offense_play, defense_play, offense_receives_2h_kickoff, change_of_poss, score_pts, score_diff_start, score_diff,
                                        offense_score, defense_score, offense_conference, defense_conference, off_timeout_called, def_timeout_called, offense_timeouts, defense_timeouts,
                                        off_timeouts_rem_before, def_timeouts_rem_before, rusher_player_name, yds_rushed, passer_player_name, receiver_player_name, yds_receiving, yds_sacked,
                                        sack_players, sack_player_name, sack_player_name2, pass_breakup_player_name, interception_player_name, yds_int_return, fumble_player_name,
                                        fumble_forced_player_name, fumble_recovered_player_name, yds_fumble_return, punter_player_name, yds_punted, punt_returner_player_name,
                                        yds_punt_return, yds_punt_gained, punt_block_player_name, punt_block_return_player_name, fg_kicker_player_name, yds_fg, fg_block_player_name,
                                        fg_return_player_name, kickoff_player_name, yds_kickoff, kickoff_returner_player_name, yds_kickoff_return, new_id, orig_drive_number, drive_number,
                                        drive_result_detailed, new_drive_pts, drive_id, drive_result, drive_start_yards_to_goal, drive_end_yards_to_goal, drive_yards, drive_scoring,
                                        drive_pts, drive_start_period, drive_end_period, drive_time_minutes_start, drive_time_seconds_start, drive_time_minutes_end, drive_time_seconds_end,
                                        drive_time_minutes_elapsed, drive_time_seconds_elapsed, drive_numbers, number_of_drives, pts_scored, drive_result_detailed_flag, drive_result2,
                                        drive_num, lag_drive_result_detailed, lead_drive_result_detailed, lag_new_drive_pts, id_drive, rush, rush_td, pass, pass_td, completion, pass_attempt,
                                        target, sack_vec, sack, int, int_td, turnover_vec, turnover_vec_lag, turnover_indicator, kickoff_play, receives_2h_kickoff, missing_yard_flag,
                                        scoring_play, td_play, touchdown, safety, fumble_vec, kickoff_tb, kickoff_onside, kickoff_oob, kickoff_fair_catch, kickoff_downed, kickoff_safety,
                                        kick_play, punt, punt_play, punt_tb, punt_oob, punt_fair_catch, punt_downed, punt_safety, punt_blocked, penalty_safety, fg_inds, fg_made,
                                        fg_make_prob, no_score_before, fg_before, opp_fg_before, opp_safety_before, opp_td_before, safety_before, td_before, no_score_after, fg_after,
                                        opp_fg_after, opp_safety_after, opp_td_after, safety_after, td_after, position_reception, position_target, position_completion, position_incompletion,
                                        position_sack_taken, position_sack, position_interception_thrown, position_interception, position_fumble, position_fumble_forced,
                                        position_fumble_recovered, position_pass_breakup, position_rush, position_touchdown, season, opponent, team_score, opponent_score, rush_player_id,
                                        rush_player, rush_yds, reception_player_id, reception_player, reception_yds, completion_player_id, completion_player, completion_yds,
                                        interception_player_id, interception_player, interception_stat, interception_thrown_player_id, interception_thrown_player, interception_thrown_stat,
                                        touchdown_player_id, touchdown_player, touchdown_stat, incompletion_player_id, incompletion_player, incompletion_stat, target_player_id,
                                        target_player, target_stat, fumble_recovered_player_id, fumble_recovered_player, fumble_recovered_stat, fumble_forced_player_id, fumble_forced_player,
                                        fumble_forced_stat, fumble_player_id, fumble_player, fumble_stat, sack_player_id, sack_player, sack_stat, sack_taken_player_id, sack_taken_player,
                                        sack_taken_stat, pass_breakup_player_id, pass_breakup_player, pass_breakup_stat, play_id, penalty_flag, penalty_declined, penalty_no_play,
                                        penalty_offset, penalty_text, penalty_play_text, row, drive_event_number, lag_play_type2, lag_play_type3, lag_play_text, lag_play_text2,
                                        lead_play_text, lag_first_by_penalty, lag_first_by_penalty2, lag_first_by_yards, lag_first_by_yards2, first_by_penalty, first_by_yards,
                                        play_after_turnover, lag_change_of_poss, lag_change_of_pos_team, lag_change_of_pos_team2, lag_kickoff_play, lag_punt, lag_punt2, lag_scoring_play,
                                        lag_turnover_vec, lag_downs_turnover, lag_defense_score_play, home_score, priority, away_score, date, text, type_id, end_yard_line,
                                        end_yards_to_endzone, drive_description, drive_short_display_result, season_type, home_team_spread, game_spread, home_favorite, game_spread_available,
                                        time, clock_minutes_2, clock_seconds_2, start_quarter_seconds_remaining, start_game_seconds_remaining, end_defteam_name, home_timeout_called,
                                        away_timeout_called, end_quarter_seconds_remaining, end_game_seconds_remaining, end_posteam_timeouts, end_yard, end_yardline_100, scoring_play_2,
                                        start_away_score, end_home_score, posteam_score_pts, end_posteam_receives_2h_kickoff, penalty_in_text, pos_unit, def_pos_unit, special_teams, play,
                                        scrimmage_play, posteam_score_differential_end, kickoff_return_player_name, fumble_recovery_player_name, punt_blocked_returner_player_name,
                                        fg_blocked_player_name, punt_blocked_player_name, blocked_player_name, kicker_player_name, kick_returner_player_name, new_down, new_ydstogo,
                                        stopped_run, opportunity_run, highlight_run, short_rush_success, short_rush_attempt, power_rush_success, power_rush_attempt, standard_down,
                                        passing_down, tfl, tfl_pass, tfl_rush, havoc, havoc_pass, havoc_rush, start_posteam_spread, start_elapsed_share, start_spread_time,
                                        end_posteam_spread, end_elapsed_share, end_spread_time, ydstogo, ep_start_touchback, ep_start, ep_end, lag_ep_end, lag_change_of_posteam, ep_between,
                                        epa_scrimmage, epa_rush, epa_pass, epa_explosive, epa_explosive_pass, epa_explosive_rush, epa_success_standard_down, epa_success_passing_down,
                                        epa_success_pass, epa_success_rush, epa_success_epa, epa_success_standard_down_epa, epa_success_passing_down_epa, epa_success_pass_epa,
                                        epa_success_rush_epa, epa_penalty, epa_special_teams, epa_fg, epa_punt, epa_kickoff, start_exp_score_diff_touchback, start_exp_score_diff,
                                        start_exp_score_diff_time_ratio_touchback, start_exp_score_diff_time_ratio, end_exp_score_diff, end_exp_score_diff_time_ratio, wp_touchback,
                                        lead_wp_before, lead_wp_before2, wpa_base, wpa_base_nxt, wpa_base_nxt2, wpa_base_ind, wpa_base_nxt_ind, wpa_base_nxt2_ind, wpa_change, wpa_change_nxt,
                                        wpa_change_nxt2, wpa_change_ind, wpa_change_nxt_ind, wpa_change_nxt2_ind, wpa_half_end, drive_start, drive_play_index, prog_drive_epa, prog_drive_wpa,
                                        drive_offense_yards, drive_total_yards, media_id)
    from '/Users/riley.gisseman/Downloads/cfb_pbp_2002_2024.csv'
    delimiter ','
    csv header;
