drop table nfl_pbp_1999_2023;
create table nfl_pbp_1999_2023
(
    play_id                              float,
    game_id                              varchar(255),
    old_game_id                          float,
    home_team                            varchar(255),
    away_team                            varchar(255),
    season_type                          varchar(255),
    week                                 float,
    posteam                              varchar(255),
    posteam_type                         varchar(255),
    defteam                              varchar(255),
    side_of_field                        varchar(255),
    yardline_100                         float,
    game_date                            varchar(255),
    quarter_seconds_remaining            float,
    half_seconds_remaining               float,
    game_seconds_remaining               float,
    game_half                            varchar(255),
    quarter_end                          float,
    drive                                float,
    sp                                   float,
    qtr                                  float,
    down                                 float,
    goal_to_go                           float,
    time                                 varchar(255),
    yrdln                                varchar(255),
    ydstogo                              float,
    ydsnet                               float,
    description                          varchar(2550),
    play_type                            varchar(255),
    yards_gained                         float,
    shotgun                              float,
    no_huddle                            float,
    qb_dropback                          float,
    qb_kneel                             float,
    qb_spike                             float,
    qb_scramble                          float,
    pass_length                          varchar(255),
    pass_location                        varchar(255),
    air_yards                            float,
    yards_after_catch                    float,
    run_location                         varchar(255),
    run_gap                              varchar(255),
    field_goal_result                    varchar(255),
    kick_distance                        float,
    extra_point_result                   varchar(255),
    two_point_conv_result                varchar(255),
    home_timeouts_remaining              float,
    away_timeouts_remaining              float,
    timeout                              float,
    timeout_team                         varchar(255),
    td_team                              varchar(255),
    td_player_name                       varchar(255),
    td_player_id                         varchar(255),
    posteam_timeouts_remaining           float,
    defteam_timeouts_remaining           float,
    total_home_score                     float,
    total_away_score                     float,
    posteam_score                        float,
    defteam_score                        float,
    score_differential                   float,
    posteam_score_post                   float,
    defteam_score_post                   float,
    score_differential_post              float,
    no_score_prob                        float,
    opp_fg_prob                          float,
    opp_safety_prob                      float,
    opp_td_prob                          float,
    fg_prob                              float,
    safety_prob                          float,
    td_prob                              float,
    extra_point_prob                     float,
    two_point_conversion_prob            float,
    ep                                   float,
    epa                                  float,
    total_home_epa                       float,
    total_away_epa                       float,
    total_home_rush_epa                  float,
    total_away_rush_epa                  float,
    total_home_pass_epa                  float,
    total_away_pass_epa                  float,
    air_epa                              float,
    yac_epa                              float,
    comp_air_epa                         float,
    comp_yac_epa                         float,
    total_home_comp_air_epa              float,
    total_away_comp_air_epa              float,
    total_home_comp_yac_epa              float,
    total_away_comp_yac_epa              float,
    total_home_raw_air_epa               float,
    total_away_raw_air_epa               float,
    total_home_raw_yac_epa               float,
    total_away_raw_yac_epa               float,
    wp                                   float,
    def_wp                               float,
    home_wp                              float,
    away_wp                              float,
    wpa                                  float,
    vegas_wpa                            float,
    vegas_home_wpa                       float,
    home_wp_post                         float,
    away_wp_post                         float,
    vegas_wp                             float,
    vegas_home_wp                        float,
    total_home_rush_wpa                  float,
    total_away_rush_wpa                  float,
    total_home_pass_wpa                  float,
    total_away_pass_wpa                  float,
    air_wpa                              float,
    yac_wpa                              float,
    comp_air_wpa                         float,
    comp_yac_wpa                         float,
    total_home_comp_air_wpa              float,
    total_away_comp_air_wpa              float,
    total_home_comp_yac_wpa              float,
    total_away_comp_yac_wpa              float,
    total_home_raw_air_wpa               float,
    total_away_raw_air_wpa               float,
    total_home_raw_yac_wpa               float,
    total_away_raw_yac_wpa               float,
    punt_blocked                         float,
    first_down_rush                      float,
    first_down_pass                      float,
    first_down_penalty                   float,
    third_down_converted                 float,
    third_down_failed                    float,
    fourth_down_converted                float,
    fourth_down_failed                   float,
    incomplete_pass                      float,
    touchback                            float,
    interception                         float,
    punt_inside_twenty                   float,
    punt_in_endzone                      float,
    punt_out_of_bounds                   float,
    punt_downed                          float,
    punt_fair_catch                      float,
    kickoff_inside_twenty                float,
    kickoff_in_endzone                   float,
    kickoff_out_of_bounds                float,
    kickoff_downed                       float,
    kickoff_fair_catch                   float,
    fumble_forced                        float,
    fumble_not_forced                    float,
    fumble_out_of_bounds                 float,
    solo_tackle                          float,
    safety                               float,
    penalty                              float,
    tackled_for_loss                     float,
    fumble_lost                          float,
    own_kickoff_recovery                 float,
    own_kickoff_recovery_td              float,
    qb_hit                               float,
    rush_attempt                         float,
    pass_attempt                         float,
    sack                                 float,
    touchdown                            float,
    pass_touchdown                       float,
    rush_touchdown                       float,
    return_touchdown                     float,
    extra_point_attempt                  float,
    two_point_attempt                    float,
    field_goal_attempt                   float,
    kickoff_attempt                      float,
    punt_attempt                         float,
    fumble                               float,
    complete_pass                        float,
    assist_tackle                        float,
    lateral_reception                    float,
    lateral_rush                         float,
    lateral_return                       float,
    lateral_recovery                     float,
    passer_player_id                     varchar(255),
    passer_player_name                   varchar(255),
    passing_yards                        float,
    receiver_player_id                   varchar(255),
    receiver_player_name                 varchar(255),
    receiving_yards                      float,
    rusher_player_id                     varchar(255),
    rusher_player_name                   varchar(255),
    rushing_yards                        float,
    lateral_receiver_player_id           varchar(255),
    lateral_receiver_player_name         varchar(255),
    lateral_receiving_yards              float,
    lateral_rusher_player_id             varchar(255),
    lateral_rusher_player_name           varchar(255),
    lateral_rushing_yards                float,
    lateral_sack_player_id               float,
    lateral_sack_player_name             float,
    interception_player_id               varchar(255),
    interception_player_name             varchar(255),
    lateral_interception_player_id       varchar(255),
    lateral_interception_player_name     varchar(255),
    punt_returner_player_id              varchar(255),
    punt_returner_player_name            varchar(255),
    lateral_punt_returner_player_id      varchar(255),
    lateral_punt_returner_player_name    varchar(255),
    kickoff_returner_player_name         varchar(255),
    kickoff_returner_player_id           varchar(255),
    lateral_kickoff_returner_player_id   varchar(255),
    lateral_kickoff_returner_player_name varchar(255),
    punter_player_id                     varchar(255),
    punter_player_name                   varchar(255),
    kicker_player_name                   varchar(255),
    kicker_player_id                     varchar(255),
    own_kickoff_recovery_player_id       varchar(255),
    own_kickoff_recovery_player_name     varchar(255),
    blocked_player_id                    varchar(255),
    blocked_player_name                  varchar(255),
    tackle_for_loss_1_player_id          varchar(255),
    tackle_for_loss_1_player_name        varchar(255),
    tackle_for_loss_2_player_id          varchar(255),
    tackle_for_loss_2_player_name        varchar(255),
    qb_hit_1_player_id                   varchar(255),
    qb_hit_1_player_name                 varchar(255),
    qb_hit_2_player_id                   varchar(255),
    qb_hit_2_player_name                 varchar(255),
    forced_fumble_player_1_team          varchar(255),
    forced_fumble_player_1_player_id     varchar(255),
    forced_fumble_player_1_player_name   varchar(255),
    forced_fumble_player_2_team          varchar(255),
    forced_fumble_player_2_player_id     varchar(255),
    forced_fumble_player_2_player_name   varchar(255),
    solo_tackle_1_team                   varchar(255),
    solo_tackle_2_team                   varchar(255),
    solo_tackle_1_player_id              varchar(255),
    solo_tackle_2_player_id              varchar(255),
    solo_tackle_1_player_name            varchar(255),
    solo_tackle_2_player_name            varchar(255),
    assist_tackle_1_player_id            varchar(255),
    assist_tackle_1_player_name          varchar(255),
    assist_tackle_1_team                 varchar(255),
    assist_tackle_2_player_id            varchar(255),
    assist_tackle_2_player_name          varchar(255),
    assist_tackle_2_team                 varchar(255),
    assist_tackle_3_player_id            varchar(255),
    assist_tackle_3_player_name          varchar(255),
    assist_tackle_3_team                 varchar(255),
    assist_tackle_4_player_id            varchar(255),
    assist_tackle_4_player_name          varchar(255),
    assist_tackle_4_team                 varchar(255),
    tackle_with_assist                   float,
    tackle_with_assist_1_player_id       varchar(255),
    tackle_with_assist_1_player_name     varchar(255),
    tackle_with_assist_1_team            varchar(255),
    tackle_with_assist_2_player_id       varchar(255),
    tackle_with_assist_2_player_name     varchar(255),
    tackle_with_assist_2_team            varchar(255),
    pass_defense_1_player_id             varchar(255),
    pass_defense_1_player_name           varchar(255),
    pass_defense_2_player_id             varchar(255),
    pass_defense_2_player_name           varchar(255),
    fumbled_1_team                       varchar(255),
    fumbled_1_player_id                  varchar(255),
    fumbled_1_player_name                varchar(255),
    fumbled_2_player_id                  varchar(255),
    fumbled_2_player_name                varchar(255),
    fumbled_2_team                       varchar(255),
    fumble_recovery_1_team               varchar(255),
    fumble_recovery_1_yards              float,
    fumble_recovery_1_player_id          varchar(255),
    fumble_recovery_1_player_name        varchar(255),
    fumble_recovery_2_team               varchar(255),
    fumble_recovery_2_yards              float,
    fumble_recovery_2_player_id          varchar(255),
    fumble_recovery_2_player_name        varchar(255),
    sack_player_id                       varchar(255),
    sack_player_name                     varchar(255),
    half_sack_1_player_id                varchar(255),
    half_sack_1_player_name              varchar(255),
    half_sack_2_player_id                varchar(255),
    half_sack_2_player_name              varchar(255),
    return_team                          varchar(255),
    return_yards                         float,
    penalty_team                         varchar(255),
    penalty_player_id                    varchar(255),
    penalty_player_name                  varchar(255),
    penalty_yards                        float,
    replay_or_challenge                  float,
    replay_or_challenge_result           varchar(255),
    penalty_type                         varchar(255),
    defensive_two_point_attempt          float,
    defensive_two_point_conv             float,
    defensive_extra_point_attempt        float,
    defensive_extra_point_conv           float,
    safety_player_name                   varchar(255),
    safety_player_id                     varchar(255),
    season                               float,
    cp                                   float,
    cpoe                                 float,
    series                               float,
    series_success                       float,
    series_result                        varchar(255),
    order_sequence                       float,
    start_time                           varchar(255),
    time_of_day                          varchar(255),
    stadium                              varchar(255),
    weather                              varchar(255),
    nfl_api_id                           varchar(255),
    play_clock                           float,
    play_deleted                         float,
    play_type_nfl                        varchar(255),
    special_teams_play                   float,
    st_play_type                         varchar(255),
    end_clock_time                       varchar(255),
    end_yard_line                        varchar(255),
    fixed_drive                          float,
    fixed_drive_result                   varchar(255),
    drive_real_start_time                varchar(255),
    drive_play_count                     float,
    drive_time_of_possession             varchar(255),
    drive_first_downs                    float,
    drive_inside20                       float,
    drive_ended_with_score               float,
    drive_quarter_start                  float,
    drive_quarter_end                    float,
    drive_yards_penalized                float,
    drive_start_transition               varchar(255),
    drive_end_transition                 varchar(255),
    drive_game_clock_start               varchar(255),
    drive_game_clock_end                 varchar(255),
    drive_start_yard_line                varchar(255),
    drive_end_yard_line                  varchar(255),
    drive_play_id_started                float,
    drive_play_id_ended                  float,
    away_score                           float,
    home_score                           float,
    location                             varchar(255),
    result                               float,
    total                                float,
    spread_line                          float,
    total_line                           float,
    div_game                             float,
    roof                                 varchar(255),
    surface                              varchar(255),
    temp                                 float,
    wind                                 float,
    home_coach                           varchar(255),
    away_coach                           varchar(255),
    stadium_id                           varchar(255),
    game_stadium                         varchar(255),
    aborted_play                         float,
    success                              float,
    passer                               varchar(255),
    passer_jersey_number                 float,
    rusher                               varchar(255),
    rusher_jersey_number                 float,
    receiver                             varchar(255),
    receiver_jersey_number               float,
    pass                                 float,
    rush                                 float,
    first_down                           float,
    special                              float,
    play                                 float,
    passer_id                            varchar(255),
    rusher_id                            varchar(255),
    receiver_id                          varchar(255),
    name                                 varchar(255),
    jersey_number                        float,
    id                                   varchar(255),
    fantasy_player_name                  varchar(255),
    fantasy_player_id                    varchar(255),
    fantasy                              varchar(255),
    fantasy_id                           varchar(255),
    out_of_bounds                        float,
    home_opening_kickoff                 float,
    qb_epa                               float,
    xyac_epa                             float,
    xyac_mean_yardage                    float,
    xyac_median_yardage                  float,
    xyac_success                         float,
    xyac_fd                              float,
    xpass                                float,
    pass_oe                              float
);
copy nfl_pbp_1999_2023(play_id, game_id, old_game_id, home_team, away_team, season_type, week, posteam, posteam_type, defteam, side_of_field, yardline_100, game_date,
                       quarter_seconds_remaining, half_seconds_remaining, game_seconds_remaining, game_half, quarter_end, drive, sp, qtr, down, goal_to_go, time, yrdln, ydstogo, ydsnet,
                       description, play_type, yards_gained, shotgun, no_huddle, qb_dropback, qb_kneel, qb_spike, qb_scramble, pass_length, pass_location, air_yards, yards_after_catch,
                       run_location, run_gap, field_goal_result, kick_distance, extra_point_result, two_point_conv_result, home_timeouts_remaining, away_timeouts_remaining, timeout,
                       timeout_team, td_team, td_player_name, td_player_id, posteam_timeouts_remaining, defteam_timeouts_remaining, total_home_score, total_away_score, posteam_score,
                       defteam_score, score_differential, posteam_score_post, defteam_score_post, score_differential_post, no_score_prob, opp_fg_prob, opp_safety_prob, opp_td_prob, fg_prob,
                       safety_prob, td_prob, extra_point_prob, two_point_conversion_prob, ep, epa, total_home_epa, total_away_epa, total_home_rush_epa, total_away_rush_epa,
                       total_home_pass_epa, total_away_pass_epa, air_epa, yac_epa, comp_air_epa, comp_yac_epa, total_home_comp_air_epa, total_away_comp_air_epa, total_home_comp_yac_epa,
                       total_away_comp_yac_epa, total_home_raw_air_epa, total_away_raw_air_epa, total_home_raw_yac_epa, total_away_raw_yac_epa, wp, def_wp, home_wp, away_wp, wpa, vegas_wpa,
                       vegas_home_wpa, home_wp_post, away_wp_post, vegas_wp, vegas_home_wp, total_home_rush_wpa, total_away_rush_wpa, total_home_pass_wpa, total_away_pass_wpa, air_wpa,
                       yac_wpa, comp_air_wpa, comp_yac_wpa, total_home_comp_air_wpa, total_away_comp_air_wpa, total_home_comp_yac_wpa, total_away_comp_yac_wpa, total_home_raw_air_wpa,
                       total_away_raw_air_wpa, total_home_raw_yac_wpa, total_away_raw_yac_wpa, punt_blocked, first_down_rush, first_down_pass, first_down_penalty, third_down_converted,
                       third_down_failed, fourth_down_converted, fourth_down_failed, incomplete_pass, touchback, interception, punt_inside_twenty, punt_in_endzone, punt_out_of_bounds,
                       punt_downed, punt_fair_catch, kickoff_inside_twenty, kickoff_in_endzone, kickoff_out_of_bounds, kickoff_downed, kickoff_fair_catch, fumble_forced, fumble_not_forced,
                       fumble_out_of_bounds, solo_tackle, safety, penalty, tackled_for_loss, fumble_lost, own_kickoff_recovery, own_kickoff_recovery_td, qb_hit, rush_attempt, pass_attempt,
                       sack, touchdown, pass_touchdown, rush_touchdown, return_touchdown, extra_point_attempt, two_point_attempt, field_goal_attempt, kickoff_attempt, punt_attempt, fumble,
                       complete_pass, assist_tackle, lateral_reception, lateral_rush, lateral_return, lateral_recovery, passer_player_id, passer_player_name, passing_yards,
                       receiver_player_id, receiver_player_name, receiving_yards, rusher_player_id, rusher_player_name, rushing_yards, lateral_receiver_player_id,
                       lateral_receiver_player_name, lateral_receiving_yards, lateral_rusher_player_id, lateral_rusher_player_name, lateral_rushing_yards, lateral_sack_player_id,
                       lateral_sack_player_name, interception_player_id, interception_player_name, lateral_interception_player_id, lateral_interception_player_name, punt_returner_player_id,
                       punt_returner_player_name, lateral_punt_returner_player_id, lateral_punt_returner_player_name, kickoff_returner_player_name, kickoff_returner_player_id,
                       lateral_kickoff_returner_player_id, lateral_kickoff_returner_player_name, punter_player_id, punter_player_name, kicker_player_name, kicker_player_id,
                       own_kickoff_recovery_player_id, own_kickoff_recovery_player_name, blocked_player_id, blocked_player_name, tackle_for_loss_1_player_id, tackle_for_loss_1_player_name,
                       tackle_for_loss_2_player_id, tackle_for_loss_2_player_name, qb_hit_1_player_id, qb_hit_1_player_name, qb_hit_2_player_id, qb_hit_2_player_name,
                       forced_fumble_player_1_team, forced_fumble_player_1_player_id, forced_fumble_player_1_player_name, forced_fumble_player_2_team, forced_fumble_player_2_player_id,
                       forced_fumble_player_2_player_name, solo_tackle_1_team, solo_tackle_2_team, solo_tackle_1_player_id, solo_tackle_2_player_id, solo_tackle_1_player_name,
                       solo_tackle_2_player_name, assist_tackle_1_player_id, assist_tackle_1_player_name, assist_tackle_1_team, assist_tackle_2_player_id, assist_tackle_2_player_name,
                       assist_tackle_2_team, assist_tackle_3_player_id, assist_tackle_3_player_name, assist_tackle_3_team, assist_tackle_4_player_id, assist_tackle_4_player_name,
                       assist_tackle_4_team, tackle_with_assist, tackle_with_assist_1_player_id, tackle_with_assist_1_player_name, tackle_with_assist_1_team, tackle_with_assist_2_player_id,
                       tackle_with_assist_2_player_name, tackle_with_assist_2_team, pass_defense_1_player_id, pass_defense_1_player_name, pass_defense_2_player_id,
                       pass_defense_2_player_name, fumbled_1_team, fumbled_1_player_id, fumbled_1_player_name, fumbled_2_player_id, fumbled_2_player_name, fumbled_2_team,
                       fumble_recovery_1_team, fumble_recovery_1_yards, fumble_recovery_1_player_id, fumble_recovery_1_player_name, fumble_recovery_2_team, fumble_recovery_2_yards,
                       fumble_recovery_2_player_id, fumble_recovery_2_player_name, sack_player_id, sack_player_name, half_sack_1_player_id, half_sack_1_player_name, half_sack_2_player_id,
                       half_sack_2_player_name, return_team, return_yards, penalty_team, penalty_player_id, penalty_player_name, penalty_yards, replay_or_challenge,
                       replay_or_challenge_result, penalty_type, defensive_two_point_attempt, defensive_two_point_conv, defensive_extra_point_attempt, defensive_extra_point_conv,
                       safety_player_name, safety_player_id, season, cp, cpoe, series, series_success, series_result, order_sequence, start_time, time_of_day, stadium, weather, nfl_api_id,
                       play_clock, play_deleted, play_type_nfl, special_teams_play, st_play_type, end_clock_time, end_yard_line, fixed_drive, fixed_drive_result, drive_real_start_time,
                       drive_play_count, drive_time_of_possession, drive_first_downs, drive_inside20, drive_ended_with_score, drive_quarter_start, drive_quarter_end, drive_yards_penalized,
                       drive_start_transition, drive_end_transition, drive_game_clock_start, drive_game_clock_end, drive_start_yard_line, drive_end_yard_line, drive_play_id_started,
                       drive_play_id_ended, away_score, home_score, location, result, total, spread_line, total_line, div_game, roof, surface, temp, wind, home_coach, away_coach, stadium_id,
                       game_stadium, aborted_play, success, passer, passer_jersey_number, rusher, rusher_jersey_number, receiver, receiver_jersey_number, pass, rush, first_down, special,
                       play, passer_id, rusher_id, receiver_id, name, jersey_number, id, fantasy_player_name, fantasy_player_id, fantasy, fantasy_id, out_of_bounds, home_opening_kickoff,
                       qb_epa, xyac_epa, xyac_mean_yardage, xyac_median_yardage, xyac_success, xyac_fd, xpass, pass_oe)
    from '/Users/riley.gisseman/Downloads/nfl_pbp_1999_2023.csv'
    delimiter ','
    csv header;